[pytest]

addopts = -v -s --disable-warnings --cov=app --cov-report=term-missing --cov-report=html

testpaths = test

filterwarnings=
    ignore::DeprecationWarning
    ignore::UserWarning

[coverage:run]
# 2. The Omit Rule (Crucial)
# This tells the coverage tracker to completely ignore files that don't need tests.
# If you don't omit your migrations, you will never reach 100% coverage.
omit =
    app/alembic/*
    app/tests/*
    */__init__.py
    app/todos.py


[coverage:report]
# 3. The Exclusion Rules
# Sometimes you have code that is physically impossible to test or is just for debugging.
# If you put "# pragma: no cover" next to a line of Python, this rule tells pytest-cov to ignore it.
exclude_lines =
    pragma: no cover
    def __repr__
    if __name__ == .__main__.: