"""added lodge table and new relationships

Revision ID: 0b57713b53c8
Revises: e77b7e1fc5e0
Create Date: 2026-04-27 19:18:52.333441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b57713b53c8'
down_revision: Union[str, Sequence[str], None] = 'e77b7e1fc5e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lodges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('landlord_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lodge_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_rooms_room_no'))
        batch_op.create_index(batch_op.f('ix_rooms_room_no'), ['room_no'], unique=False)
        batch_op.create_unique_constraint('lodge_room_uc', ['room_no', 'lodge_id'])
        batch_op.create_foreign_key("fk_rooms_lodge_id_lodges", 'lodges', ['lodge_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('lodge_room_uc', type_='unique')
        batch_op.drop_index(batch_op.f('ix_rooms_room_no'))
        batch_op.create_index(batch_op.f('ix_rooms_room_no'), ['room_no'], unique=1)
        batch_op.drop_column('lodge_id')

    op.drop_table('lodges')
    # ### end Alembic commands ###
