"""Initial migration

Revision ID: fc32d116fad1
Revises: 
Create Date: 2026-05-05 19:49:35.530148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc32d116fad1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('phone_no', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('LANDLORD', 'TENANT', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_phone_no'), ['phone_no'], unique=False)

    op.create_table('lodges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lodge_id', sa.Integer(), nullable=False),
    sa.Column('tenant_type', sa.Enum('STUDENT', 'OTHERS', name='tenanttype'), nullable=False),
    sa.Column('emergency_contact_name', sa.String(length=20), nullable=False),
    sa.Column('emergency_contact_phone_no', sa.String(), nullable=False),
    sa.Column('level', sa.Enum('LEVEL_100', 'LEVEL_200', 'LEVEL_300', 'LEVEL_400', 'LEVEL_500', 'LEVEL_600', name='studentlevel'), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('reg_no', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lodge_id'], ['tenant_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lodge_id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('tenant_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_profiles_emergency_contact_name'), ['emergency_contact_name'], unique=False)

    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lodge_id', sa.Integer(), nullable=True),
    sa.Column('room_no', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('base_rent_price', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('VACANT', 'OCCUPIED', 'MAINTENANCE', name='roomstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lodge_id'], ['lodges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_no', 'lodge_id', name='lodge_room_uc')
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rooms_room_no'), ['room_no'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rooms_room_no'))

    op.drop_table('rooms')
    with op.batch_alter_table('tenant_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_profiles_emergency_contact_name'))

    op.drop_table('tenant_profiles')
    op.drop_table('lodges')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone_no'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
